"""Explicit pinned downloads; never execute the downloaded model source."""
import argparse,json,shutil,tarfile
from pathlib import Path
from common import fetch,sha256,verify,write_report
from download_checkpoints import FILES,REVISION

MOL_REVISION='4c912b450175f31b5ba913a5dc921c03b27b985a'
MOL_SHA='a443592193075334b55483501f1e04cdf4ef9c461db103f687ba4335b036cf14'
MOL_SIZE=181651424
ASSET_SHA='39e076d96dbec6b4e86982bbda16f3a53a2a60c9bdc17828d88f6f9a0c7d1fd7'
ASSET_SIZE=1855662080


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('target',choices=['moljepa','boltz2','boltz2-molecules'])
    parser.add_argument('--directory',type=Path,required=True)
    args=parser.parse_args();root=args.directory;root.mkdir(parents=True,exist_ok=True)
    if args.target=='moljepa':
        provenance=json.loads((Path(__file__).parent/'moljepa-source.json').read_text())
        architecture=root/'architecture';architecture.mkdir(exist_ok=True)
        for name in provenance['upstream_code_files_unmodified']:
            fetch(f'https://huggingface.co/Flogrammer/Mol-JEPA/resolve/{MOL_REVISION}/{name}',
                  architecture/name,provenance['sha256'][name])
        for name,local in [('__init__.py','moljepa-init.txt'),('LICENSE.txt','MOLJEPA_LICENSE.txt')]:
            original=Path(__file__).parent/local;verify(original,provenance['sha256'][name])
            if not (architecture/name).exists():shutil.copyfile(original,architecture/name)
            verify(architecture/name,provenance['sha256'][name])
        source=architecture/'SOURCE.json'
        if source.exists() and json.loads(source.read_text())!=provenance:raise ValueError('Existing source manifest differs')
        if not source.exists():write_report(source,provenance)
        fetch(f'https://huggingface.co/Flogrammer/Mol-JEPA/resolve/{MOL_REVISION}/model.safetensors',
              root/'model.safetensors',MOL_SHA,MOL_SIZE)
    elif args.target=='boltz2':
        for name,(size,digest) in FILES.items():
            fetch(f'https://huggingface.co/boltz-community/boltz-2/resolve/{REVISION}/{name}',root/name,digest,size)
    else:
        archive=fetch(f'https://huggingface.co/boltz-community/boltz-2/resolve/{REVISION}/mols.tar',root/'mols.tar',ASSET_SHA,ASSET_SIZE)
        # The fixture only needs canonical residues/nucleotides. SMILES ligand
        # molecules are generated by the upstream parser. No tar.extract call.
        import ast,importlib.util
        from compressme.boltz2_io import _architecture,_verify_local_boltz
        source,_=_architecture(Path(__import__('compressme.boltz2_io',fromlist=['x']).__file__).parent/'data/boltz2')
        package=_verify_local_boltz(source)
        tree=ast.parse((package/'data/const.py').read_text())
        tokens=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign)
                    and any(isinstance(t,ast.Name) and t.id=='canonical_tokens' for t in n.targets))
        wanted={f'mols/{token}.pkl' for token in tokens};seen=set();records=[]
        destination=root/'mols';destination.mkdir(exist_ok=True)
        with tarfile.open(archive,'r:') as handle:
            for member in handle:
                if member.name not in wanted:continue
                if member.name in seen or not member.isfile() or member.size>2<<20:raise ValueError('Unexpected molecular asset')
                seen.add(member.name);raw=handle.extractfile(member).read();path=destination/Path(member.name).name
                if path.exists() and path.read_bytes()!=raw:raise ValueError('Existing molecule differs')
                if not path.exists():path.write_bytes(raw)
                records.append({'file':path.name,'bytes':len(raw),'sha256':sha256(path)})
        if seen!=wanted:raise ValueError('Missing canonical molecular assets')
        report={'archive_sha256':ASSET_SHA,'archive_bytes':ASSET_SIZE,'assets':records,
                'trust_boundary':'Upstream parser subsequently unpickles verified RDKit molecule assets; neural checkpoint pickle is never executed.'}
        record_path=root/'molecular-assets.json'
        if record_path.exists() and json.loads(record_path.read_text())!=report:raise ValueError('Existing molecular manifest differs; use a new directory')
        if not record_path.exists():write_report(record_path,report)
    print(json.dumps({'target':args.target,'directory':str(root.resolve()),'verified':True,'downloaded_python_executed':False}))

if __name__=='__main__':main()
